import Head from 'next/head';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Unaport',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <link rel="icon" href="/assets/Unaport_Logo.png" type="image/png" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>

      <html lang="en">
        <body suppressHydrationWarning={true} className={inter.className}>
          {children}
        </body>
      </html>
    </>
  );
}
